### ISSUE TITLE
大神，你好，我运行命令` npm run electron:build`报错如下所示：

### ISSUE THREAD

**Issue by wangyesheng** [jzfai/vue3-admin-electron#2]
这是 terminal 提示：
![image](https://user-images.githubusercontent.com/42696348/151646341-4a4e892c-7596-475e-ae50-38c2de35fec5.png)
这是错误日志：
![image](https://user-images.githubusercontent.com/42696348/151646362-a229c398-1dfc-4b7a-9c25-afa0070a8331.png)

**Comment by jzfai** [comment]
请升级下你的node版本
