### ISSUE TITLE
安装包安装后打开 登录报错

### ISSUE THREAD

**Issue by Corgis** [jzfai/vue3-admin-electron#3]
![image](https://user-images.githubusercontent.com/13865529/154181090-32e57623-32dc-4fd1-8770-2874cb9f4fc0.png)

**Comment by jzfai** [comment]
不存在这个问题喔，请来取代码重新测试下

**Comment by Corgis** [comment]
> 不存在这个问题喔，请来取代码重新测试下

哦，我是下载了你提供的百度网盘的exe安装的，那我拉取代码跑一下。

**Comment by jzfai** [comment]
哦，你用代码测试下，百度网盘的没有更新喔
