### ISSUE TITLE
服务启动中......

### ISSUE THREAD

**Issue by Blizzard-liu** [jzfai/vue3-admin-electron#4]
第一次启动的时候一直是等待页面   重新启动下就好了  大佬  知道啥原因吗

**Comment by Blizzard-liu** [comment]
![image](https://user-images.githubusercontent.com/20244432/158720175-99b9ae55-23fb-40ca-b7d8-0bd55d65f81f.png)
大佬 waitOn 这段代码是干啥的  好像经常卡在loading.html

**Comment by Blizzard-liu** [comment]
![image](https://user-images.githubusercontent.com/20244432/159193135-a37045f5-3eca-4911-9e36-e5c38acfecde.png)
报错信息

**Comment by Blizzard-liu** [comment]
好像是每天第一次启动的时候必报错

**Comment by jzfai** [comment]
已经fix
